// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkGvkhMMH3Hws8KMkIgppDFgeDuRQkU04',
    appId: '1:1096126684447:web:2283b6f1eeaaee5b8ce42a',
    messagingSenderId: '1096126684447',
    projectId: 'inclass14-cloudmessage',
    authDomain: 'inclass14-cloudmessage.firebaseapp.com',
    storageBucket: 'inclass14-cloudmessage.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqk-cnU8r4WagXPo2vn5LjwfbuK6eISDQ',
    appId: '1:1096126684447:android:ccc2b7c1221b83458ce42a',
    messagingSenderId: '1096126684447',
    projectId: 'inclass14-cloudmessage',
    storageBucket: 'inclass14-cloudmessage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnj2xf1uRAPpcb9bh55OEgrs-UMyt9W_k',
    appId: '1:1096126684447:ios:2c2bb88afbb5bb7b8ce42a',
    messagingSenderId: '1096126684447',
    projectId: 'inclass14-cloudmessage',
    storageBucket: 'inclass14-cloudmessage.firebasestorage.app',
    iosBundleId: 'com.example.act14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnj2xf1uRAPpcb9bh55OEgrs-UMyt9W_k',
    appId: '1:1096126684447:ios:2c2bb88afbb5bb7b8ce42a',
    messagingSenderId: '1096126684447',
    projectId: 'inclass14-cloudmessage',
    storageBucket: 'inclass14-cloudmessage.firebasestorage.app',
    iosBundleId: 'com.example.act14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkGvkhMMH3Hws8KMkIgppDFgeDuRQkU04',
    appId: '1:1096126684447:web:4e9290591f00d4c08ce42a',
    messagingSenderId: '1096126684447',
    projectId: 'inclass14-cloudmessage',
    authDomain: 'inclass14-cloudmessage.firebaseapp.com',
    storageBucket: 'inclass14-cloudmessage.firebasestorage.app',
  );
}
